---
{{ if .Values.image_pull_secret.enabled and .Values.image_pull_secret.create_sealed_secret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.image_pull_secret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.image_pull_secret.encrypted_value }}
  template:
    metadata:
      name: {{ .Values.image_pull_secret.name }}
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson
{{ end }}