apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.container_port }}
      targetPort: 80
  selector:
    app: {{ .Values.frontend.name }}